version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/atyagi9006/depre-demo:local
    container_name: depre-demo-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    networks:
      - app-network

  # Development service with volume mounts for live reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: ghcr.io/atyagi9006/depre-demo:dev
    container_name: depre-demo-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: node server.js
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge