# Docker Compose configuration for forever-running Hoek demo server

services:
  forever-server:
    build:
      context: .
      dockerfile: Dockerfile.forever
    image: ghcr.io/atyagi9006/depre-demo:forever
    container_name: depre-demo-forever
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - NODE_OPTIONS=--max-old-space-size=256
    restart: always  # Always restart the container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - forever-network
    volumes:
      - ./logs:/app/logs  # Persist logs

  # Optional monitoring with auto-restart
  monitor:
    image: alpine:latest
    container_name: depre-demo-monitor
    depends_on:
      - forever-server
    restart: always
    command: |
      sh -c "
        while true; do
          if wget -q --spider http://forever-server:8080/health; then
            echo '[SUCCESS] Health check passed at: '`date`
          else
            echo '[ERROR] Health check failed at: '`date`
          fi
          sleep 60
        done
      "
    networks:
      - forever-network

networks:
  forever-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  logs:
    driver: local